version: "3.8"

services :

  frontend:
    build:
      context: ./Frontend/dashboard/.
      dockerfile: Dockerfile
    container_name: react_build
    tty: true
    volumes:
      - ./Frontend/dashboard/dist:/src/dist
    depends_on:
      - backend
    networks:
      - dash_net

  backend:
    build:
      context: ./Backend/.
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: always
    tty: true
    ports:
      - 8888:8888
    networks:
      - dash_net

  nginx:
    build:
      context: ./Nginx/.
      dockerfile: Dockerfile
    container_name: dashboard_nginx
    restart: always
    tty: true
    networks:
      - dash_net
    ports:
      - "80:80"
    volumes:
      - ./Frontend/dashboard/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend


networks:
  dash_net:
    driver: bridge