services :

  backend:
    build:
      context: ./Backend/server/.
      dockerfile: Dockerfile
    container_name: spring_backend
    restart: always
    tty: true
    volumes:
      - ./Backend/server/:/app/
    ports:
      - "8081:8080"
    networks:
      - dash_net

  nginx:
    build:
      context: ./Nginx/.
      dockerfile: Dockerfile
    container_name: dashboard_nginx
    restart: always
    tty: true
    networks:
      - dash_net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Frontend/dashboard/dist:/usr/share/nginx/html
      - ./Nginx/conf.d:/etc/nginx/conf.d
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      # 해당 경로는 init-letsencrypt.sh 내 data_path와 일치화 필요!
      - ./Nginx/data/certbot/conf:/etc/letsencrypt
      - ./Nginx/data/certbot/www:/var/www/certbot
      - ./Nginx/fail2ban/jail.conf:/etc/fail2ban/jail.conf
      - ./Nginx/fail2ban/jail.conf:/etc/fail2ban/jail.local
      - ./Nginx/fail2ban/filter.d/:/etc/fail2ban/filter.d/
      - ./Nginx/modsecurity/modsecurity.conf:/usr/local/nginx/conf/modsecurity.conf
      - ./Nginx/modsecurity/modsec_includes.conf:/usr/local/nginx/conf/modsec_includes.conf
      - ./Nginx/modsecurity/crs-setup.conf:/usr/local/nginx/conf/rules/crs-setup.conf
      - ./Nginx/logs/nginx/:/usr/local/nginx/logs/
      - ./Nginx/logs/ts_nginx/:/var/log/nginx/
      - ./Nginx/logs/total/:/var/log/
    depends_on:
      - backend


  # certbot 자동 갱신을 위한 도커
  certbot:
    image: certbot/certbot
    volumes:
      # 해당 경로는 init-letsencrypt.sh 내 data_path와 일치화 필요!
      - ./Nginx/data/certbot/conf:/etc/letsencrypt
      - ./Nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 720h & wait $${!}; done;'"


networks:
  dash_net:
    driver: bridge