FROM openjdk:17-slim

ENV APP_NAME=Dashboard-0.0.1-SNAPSHOT
ENV APP_VERSION=0.9.0
ENV JAR_FILE=${APP_NAME}.jar

WORKDIR /app

ENTRYPOINT ["java", "-jar", "/app/Dashboard-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080